### ISSUE TITLE
Rework dep management

### ISSUE THREAD

**Issue by brendangibat** [brendangibat/terraform-provider-kubernetes#1]
Should be able to perform a 'go get' for installation in a go environment.

**Comment by brendangibat** [comment]
Alternatively use a makefile

**Comment by kelcecil** [comment]
Why not stick with glide? glide seems to work pretty well.

**Comment by brendangibat** [comment]
@kelcecil yeah I think I will. I don't want to go back and redo everything since the dep management is crazy until the k8s client imports get updated to their rework.

**Comment by brendangibat** [comment]
@kelcecil I added a makefile so the ticket was satisfied
