### ISSUE TITLE
Replication Controller delete removes the replication controller but not pods

### ISSUE THREAD

**Issue by kelcecil** [brendangibat/terraform-provider-kubernetes#13]
Deleting a replication controller removes the replication controller resource, but it does not appear to delete the associated pods with it. The expected behavior would be that the replication controller and associated pods would all be removed on a delete.

**Comment by brendangibat** [comment]
Yep, I noticed this as well and forgot to ticket it.

**Comment by brendangibat** [comment]
I'm working on this
