### ISSUE TITLE
Failing provider validation

### ISSUE THREAD

**Issue by mattnenterprise** [brendangibat/terraform-provider-kubernetes#17]
- provider.kubernetes: Internal validation of the provider failed! This is always a bug
  with the provider itself, and not a user issue. Please report
  this bug:

kubernetes_service: session_affinity: Default cannot be set with Required

**Comment by mattnenterprise** [comment]
@brendangibat The spec shows the session affinity as optional?

**Comment by brendangibat** [comment]
I was looking at: https://github.com/kubernetes/kubernetes/blob/release-1.0/pkg/api/types.go#L1147

But I messed up on configuring the service spec.
